//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesEventInvitees
    {
        public int AttendeeID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public string Attendence { get; set; }
        public Nullable<int> SiteUserID { get; set; }
    }
}
