//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesNotes
    {
        public int NoteID { get; set; }
        public int SiteCoID { get; set; }
        public int SiteUserID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Subject { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
