//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoActivitiesStatus
    {
        public CoActivitiesStatus()
        {
            this.ActivitiesCalls = new HashSet<ActivitiesCalls>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> StatusOrder { get; set; }
        public int SiteCoID { get; set; }
    
        public virtual ICollection<ActivitiesCalls> ActivitiesCalls { get; set; }
    }
}
