//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoAreas
    {
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public int SiteCoID { get; set; }
        public Nullable<int> AreaOrder { get; set; }
    }
}
