//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoCalendarGroupMembers
    {
        public int CalendarGroupMemberID { get; set; }
        public Nullable<int> CalendarGroupID { get; set; }
        public Nullable<int> CalendarGroupMember { get; set; }
    }
}
