//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoCalendar
    {
        public int CalendarID { get; set; }
        public string CalendarName { get; set; }
        public Nullable<decimal> Monday { get; set; }
        public Nullable<decimal> Tuesday { get; set; }
        public Nullable<decimal> Wednesday { get; set; }
        public Nullable<decimal> Thursday { get; set; }
        public Nullable<decimal> Friday { get; set; }
        public Nullable<decimal> Saturday { get; set; }
        public Nullable<decimal> Sunday { get; set; }
        public Nullable<decimal> DailyStartTime { get; set; }
        public Nullable<decimal> BreakTime { get; set; }
        public Nullable<decimal> BufferTime { get; set; }
        public int SiteCoID { get; set; }
    }
}
