//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoCallPurposes
    {
        public CoCallPurposes()
        {
            this.ActivitiesCalls = new HashSet<ActivitiesCalls>();
        }
    
        public int CallPurposeID { get; set; }
        public string PurposeName { get; set; }
        public Nullable<int> CallPurposeOrder { get; set; }
        public int SiteCoID { get; set; }
    
        public virtual ICollection<ActivitiesCalls> ActivitiesCalls { get; set; }
    }
}
