//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoContactCustom
    {
        public int CoContactCustomID { get; set; }
        public int SiteCoID { get; set; }
        public string Custom1 { get; set; }
        public Nullable<bool> ShowCustom1 { get; set; }
        public string Custom2 { get; set; }
        public Nullable<bool> ShowCustom2 { get; set; }
        public string Custom3 { get; set; }
        public Nullable<bool> ShowCustom3 { get; set; }
        public string Custom4 { get; set; }
        public Nullable<bool> ShowCustom4 { get; set; }
    }
}
