//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoContactPhones
    {
        public int ContactPhoneID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Ext { get; set; }
    
        public virtual CoContacts CoContacts { get; set; }
        public virtual SiteContactPhoneTypes SiteContactPhoneTypes { get; set; }
    }
}
