//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoCorStatus
    {
        public int CorStatusID { get; set; }
        public string CorStatus { get; set; }
        public Nullable<int> ChangeRequestOrder { get; set; }
        public Nullable<bool> CorLocked { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
