//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoDataOptions
    {
        public int MasterItemID { get; set; }
        public Nullable<int> OptionMasterItemID { get; set; }
        public Nullable<decimal> OptionQuantity { get; set; }
        public Nullable<bool> OptionSummarize { get; set; }
    }
}
