//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoDataSpecs
    {
        public int MasterItemID { get; set; }
        public Nullable<decimal> ItemHeight { get; set; }
        public Nullable<decimal> ItemWidth { get; set; }
        public Nullable<decimal> ItemDepth { get; set; }
        public Nullable<decimal> ItemRackUnits { get; set; }
        public Nullable<decimal> ItemLength { get; set; }
        public Nullable<decimal> ItemWeight { get; set; }
        public Nullable<decimal> ItemArea { get; set; }
        public Nullable<decimal> ItemVolume { get; set; }
        public Nullable<decimal> ItemAmps { get; set; }
        public Nullable<decimal> ItemVoltage { get; set; }
        public Nullable<decimal> ItemBtu { get; set; }
    }
}
