//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoData
    {
        public int MasterItemID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> SubGroupID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string Model { get; set; }
        public string SKU { get; set; }
        public string Type { get; set; }
        public string ProductDescription { get; set; }
        public string SalesDescription { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Hyperlink { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> CostCodeID { get; set; }
        public byte[] ItemImage { get; set; }
        public Nullable<int> CostUomID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SellUomID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> EstHrs { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public string OrderingName { get; set; }
        public Nullable<bool> UseOrderingName { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> ResourceQty { get; set; }
        public Nullable<bool> ExcludePOR { get; set; }
        public Nullable<bool> ExcludeSO { get; set; }
        public Nullable<int> ReOrderQuantity { get; set; }
        public Nullable<bool> SalesTaxed { get; set; }
        public Nullable<bool> PurchasedTaxed { get; set; }
        public Nullable<bool> LaborTaxed { get; set; }
        public string AcctItemID { get; set; }
        public Nullable<bool> WarranteePart { get; set; }
        public Nullable<bool> OneLabelQuantity { get; set; }
        public Nullable<bool> OneOffPart { get; set; }
        public Nullable<int> SalesUnitID { get; set; }
        public Nullable<int> OrderUnitID { get; set; }
    }
}
