//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoKitItems
    {
        public int KitItemID { get; set; }
        public Nullable<int> MasterKitID { get; set; }
        public Nullable<int> MasterItemID { get; set; }
        public Nullable<decimal> KitItemQuantity { get; set; }
    }
}
