//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoLeadQuestions
    {
        public int CoLeadQID { get; set; }
        public int SiteCoID { get; set; }
        public string LeadQ { get; set; }
        public Nullable<int> LeadQTypeID { get; set; }
    }
}
