//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoOptions
    {
        public string PoNumFormat { get; set; }
        public Nullable<int> PoCounter { get; set; }
        public string SoNumFormat { get; set; }
        public Nullable<int> SoCounter { get; set; }
        public string WoNumFormat { get; set; }
        public Nullable<int> WoCounter { get; set; }
        public string QuoteNumFormat { get; set; }
        public Nullable<int> QuoteCounter { get; set; }
        public string JobNumFormat { get; set; }
        public Nullable<int> JobCounter { get; set; }
        public string DeliveryNumFormat { get; set; }
        public Nullable<int> DeliveryCounter { get; set; }
        public string CoNumFormat { get; set; }
        public Nullable<int> CoCounter { get; set; }
        public string SrQuoteNumFormat { get; set; }
        public Nullable<int> SrQuoteCounter { get; set; }
        public string TransNumFormat { get; set; }
        public Nullable<int> TransCounter { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public int SiteCoID { get; set; }
    }
}
