//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoPayTypes
    {
        public int PayTypeID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public string PayType { get; set; }
        public Nullable<int> PayTypeNumber { get; set; }
        public Nullable<decimal> PayTypeFactor { get; set; }
    }
}
