//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoProjectStatus
    {
        public int ProjectStatusID { get; set; }
        public string ProjectStatusName { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
        public Nullable<int> ProjectStatusOrder { get; set; }
        public Nullable<bool> Lock { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
