//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoProfiles
    {
        public int CoProfileID { get; set; }
        public int SiteCoID { get; set; }
        public string ProfileName { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> ProfileOrder { get; set; }
    }
}
