//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoQuoteWerks
    {
        public int QuoteWerksID { get; set; }
        public string StageField { get; set; }
        public string AreaField { get; set; }
        public string DivisionField { get; set; }
        public string DocsDatabase { get; set; }
        public string ProductsDatabase { get; set; }
        public string DefaultManufacturer { get; set; }
        public string DefaultVendor { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
