//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoQuickBooks
    {
        public int SiteCoID { get; set; }
        public string apiKey { get; set; }
        public string apiSecret { get; set; }
        public byte[] AccessToken { get; set; }
        public string QuickBooksUserName { get; set; }
        public string QuickBooksPassword { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RedirectUrl { get; set; }
        public string RealmID { get; set; }
        public string DataSource { get; set; }
    }
}
