//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoReportDefaults
    {
        public int ReportDefaultID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> PorID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> ServiceWoID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
