//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSalezToolz
    {
        public int SiteUserID { get; set; }
        public string SalezToolzUserID { get; set; }
        public string DisplayName { get; set; }
        public string RealmID { get; set; }
        public string OAuthAccessToken { get; set; }
        public string OAuthAccessTokenSecret { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RedirectUrl { get; set; }
    }
}
