//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoServiceNumFormats
    {
        public int NumID { get; set; }
        public int SiteCoID { get; set; }
        public string NumData { get; set; }
        public string NumSep { get; set; }
        public Nullable<decimal> NumStart { get; set; }
    }
}
