//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSecurityProfiles
    {
        public int CoSecurityProfileID { get; set; }
        public int SiteCoID { get; set; }
        public Nullable<int> CoProfileID { get; set; }
        public int SecuritySectionID { get; set; }
        public Nullable<bool> SecurityView { get; set; }
        public Nullable<bool> SecurityCreate { get; set; }
        public Nullable<bool> SecurityEdit { get; set; }
        public Nullable<bool> SecurityAdmin { get; set; }
    }
}
