//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoStagesMaster
    {
        public int StageMasterID { get; set; }
        public string StageName { get; set; }
        public Nullable<int> StageOrder { get; set; }
        public Nullable<int> CostCodeID { get; set; }
        public Nullable<decimal> StageMiscEquipAdjt { get; set; }
        public Nullable<decimal> StageMiscPartsAdjt { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
