//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoTaxes
    {
        public int MasterTaxID { get; set; }
        public string TaxCode { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<decimal> SalesRate { get; set; }
        public Nullable<decimal> LaborRate { get; set; }
        public Nullable<decimal> CostRate { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
