//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollID { get; set; }
        public Nullable<int> PayrollTypeID { get; set; }
        public Nullable<int> PayrollEventID { get; set; }
        public Nullable<int> SubmitUserID { get; set; }
        public Nullable<decimal> SubmittedHours { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.TimeSpan> SubmitTime { get; set; }
        public string SubmitSigned { get; set; }
        public Nullable<int> ProjectApproverID { get; set; }
        public Nullable<System.DateTime> ProjectApprovedDate { get; set; }
        public Nullable<System.TimeSpan> ProjectApprovedTime { get; set; }
        public Nullable<int> EmployeeApproverID { get; set; }
        public Nullable<System.DateTime> EmployeeApprovedDate { get; set; }
        public Nullable<System.TimeSpan> EmployeeApprovedTime { get; set; }
        public Nullable<int> PayrollStatusID { get; set; }
        public string AcctID { get; set; }
        public Nullable<int> PayrollPeriodItemID { get; set; }
    }
}
