//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollReasons
    {
        public int PayrollReasonID { get; set; }
        public int PayrollID { get; set; }
        public Nullable<int> SubmitUserID { get; set; }
        public Nullable<System.DateTime> PayrollReasonDate { get; set; }
        public Nullable<System.TimeSpan> PayrollReasonTime { get; set; }
        public string PayrollReasonNote { get; set; }
    }
}
