//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollItems
    {
        public int PayrollItemID { get; set; }
        public int PayrollID { get; set; }
        public Nullable<int> ProjectCostCodeID { get; set; }
        public Nullable<int> ProjectPayTypeID { get; set; }
        public Nullable<decimal> ItemHours { get; set; }
    }
}
