//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostIt
    {
        public int PostID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PostTopic { get; set; }
        public string PostBody { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<bool> PostNotify { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
        public Nullable<System.TimeSpan> PostTime { get; set; }
    }
}
