//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcurementTransferItems
    {
        public int TransferItemID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<int> FromProjectID { get; set; }
        public Nullable<int> FromPorID { get; set; }
        public Nullable<int> FromProcurementID { get; set; }
        public Nullable<int> FromItemID { get; set; }
        public Nullable<int> FromCustodyLocationID { get; set; }
        public Nullable<int> ToProjectID { get; set; }
        public Nullable<int> ToPorID { get; set; }
        public Nullable<int> ToProcurementID { get; set; }
        public Nullable<int> ToItemID { get; set; }
        public Nullable<int> ToCustodyLocationID { get; set; }
    }
}
