//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procurement
    {
        public int ProcurementID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<int> OrderQuantityID { get; set; }
        public Nullable<int> CustodyLocationID { get; set; }
        public string PackingSlipNumber { get; set; }
    }
}
