//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPurchaseOrders
    {
        public int PurchaseOrderID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ShippingMethodID { get; set; }
        public Nullable<int> ProcurementStatusID { get; set; }
        public string TrackingNumber { get; set; }
        public string Notes { get; set; }
        public string AcctPorID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> ShipToID { get; set; }
    }
}
