//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectForecastStages
    {
        public int ForecastStageID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectStageID { get; set; }
        public Nullable<System.DateTime> ForecastStartDate { get; set; }
        public Nullable<int> ForecastManpower { get; set; }
        public Nullable<int> ForecastDaysWeek { get; set; }
        public Nullable<decimal> ForecastHoursDay { get; set; }
        public Nullable<int> StageTotalDays { get; set; }
        public Nullable<int> ForecastStageColorID { get; set; }
        public Nullable<int> ForecastTemplateID { get; set; }
        public Nullable<System.DateTime> ForecastFinishDate { get; set; }
        public Nullable<int> ProjectMileStoneID { get; set; }
        public Nullable<int> DateType { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    }
}
