//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectLeadInfo
    {
        public int ProjectLeadID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LeadTypeID { get; set; }
        public Nullable<decimal> LeadBudget { get; set; }
        public Nullable<int> LeadProbabilityID { get; set; }
        public Nullable<System.DateTime> LeadCloseDate { get; set; }
        public string LeadSource { get; set; }
        public Nullable<int> LeadSystemTypeID { get; set; }
        public Nullable<System.DateTime> LeadDateModified { get; set; }
        public Nullable<int> LeadSourceTypeID { get; set; }
        public Nullable<int> RatingID { get; set; }
        public Nullable<int> StageID { get; set; }
    }
}
