//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDivisions
    {
        public int ProjectID { get; set; }
        public string DivisionName { get; set; }
        public int DivisionOrder { get; set; }
        public int ProjectDivisionID { get; set; }
    }
}
