//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectWoCheckListItems
    {
        public int ProjectWoCheckListItemID { get; set; }
        public int WoID { get; set; }
        public Nullable<int> CoWoCheckListItemID { get; set; }
        public Nullable<bool> WoCheckListItemStatusID { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
    }
}
