//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSOs
    {
        public int SoID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string SoName { get; set; }
        public string SoNumber { get; set; }
        public Nullable<int> SoTermID { get; set; }
        public Nullable<int> SoStatusID { get; set; }
        public Nullable<System.DateTime> SoDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public string AcctSoID { get; set; }
    }
}
