//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectKits
    {
        public int ProjectKitID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> MasterKitID { get; set; }
        public string ProjectKitName { get; set; }
        public string ProjectKitDescription { get; set; }
        public Nullable<decimal> ProjectKitDiscount { get; set; }
        public Nullable<bool> ProjectKitSummarize { get; set; }
    }
}
