//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTimeIts
    {
        public int TimeItID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> TimeItDate { get; set; }
        public Nullable<System.TimeSpan> TimeItTime { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProjectStageID { get; set; }
        public Nullable<int> ProjectPayTypeID { get; set; }
        public Nullable<int> ProjectCostCodeID { get; set; }
        public string AcctTimeItID { get; set; }
        public string Billing { get; set; }
        public Nullable<int> ApprovalUserID { get; set; }
        public Nullable<int> PayrollStatusID { get; set; }
    }
}
