//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStages
    {
        public int ProjectStageID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int StageMasterID { get; set; }
        public int StageSubID { get; set; }
        public Nullable<decimal> StageLaborCost { get; set; }
        public Nullable<decimal> StageLaborPrice { get; set; }
        public Nullable<decimal> StageLaborFactor { get; set; }
        public Nullable<decimal> StageDifficultyFactor { get; set; }
        public Nullable<decimal> StageMiscPartsFactor { get; set; }
        public Nullable<decimal> StageMiscProductFactor { get; set; }
        public Nullable<bool> StageIgnoreLabor { get; set; }
        public Nullable<decimal> StageMiscEquipAdjt { get; set; }
        public Nullable<decimal> StageMiscPartsAdjt { get; set; }
    }
}
