//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDesigns
    {
        public int DesignID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DesignTypeID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public byte[] DesignFiles { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileGroupID { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public string LinkID { get; set; }
    }
}
