//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItemPricing
    {
        public int ItemPriceID { get; set; }
        public int ItemID { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitHours { get; set; }
        public Nullable<int> SalesTaxID { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<bool> SalesTaxed { get; set; }
        public Nullable<bool> LaborTaxed { get; set; }
        public Nullable<bool> CostTaxed { get; set; }
        public Nullable<int> ProjectCostCodeID { get; set; }
    }
}
