//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCases
    {
        public int CaseID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Notes { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
        public Nullable<int> CaseTypeID { get; set; }
    }
}
