//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItemUpdates
    {
        public int ItemUpdateID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int ItemID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> EquipmentAdjustment { get; set; }
        public Nullable<decimal> MiscPartsAdjustment { get; set; }
        public Nullable<decimal> UnitHours { get; set; }
        public Nullable<decimal> FixedLaborPrice { get; set; }
        public Nullable<decimal> FixedLaborCost { get; set; }
        public Nullable<int> LaborCalcMethod { get; set; }
        public Nullable<int> SalesTaxID { get; set; }
        public Nullable<int> LaborTaxID { get; set; }
        public Nullable<int> CostTaxID { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> Markup { get; set; }
        public Nullable<bool> SalesTaxed { get; set; }
        public Nullable<bool> LaborTaxed { get; set; }
        public Nullable<bool> CostTaxed { get; set; }
        public Nullable<int> CORNo { get; set; }
        public Nullable<int> PORNo { get; set; }
        public Nullable<int> OldSONo { get; set; }
        public Nullable<int> NewSONo { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
