//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCommunications
    {
        public int ProjectCommID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
    }
}
