//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteLicenseOrdered
    {
        public int LicenseOrderID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
        public Nullable<int> LicenseID { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<int> LicensePriceID { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> PromoID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
        public Nullable<System.DateTime> DateConsumed { get; set; }
    }
}
