//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCompanies
    {
        public SiteCompanies()
        {
            this.ActivitiesCalls = new HashSet<ActivitiesCalls>();
        }
    
        public int CoVersionID { get; set; }
        public int CoStatusID { get; set; }
        public string CoName { get; set; }
        public string CoAddress1 { get; set; }
        public string CoAddress2 { get; set; }
        public string CoCity { get; set; }
        public string CoState { get; set; }
        public string CoZip { get; set; }
        public string CoCountry { get; set; }
        public string CoPhone { get; set; }
        public Nullable<System.DateTime> CoDateCreated { get; set; }
        public string CoAcctNumber { get; set; }
        public int SiteCoID { get; set; }
        public byte[] Logo { get; set; }
        public string License { get; set; }
    
        public virtual ICollection<ActivitiesCalls> ActivitiesCalls { get; set; }
    }
}
