//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUsers
    {
        public SiteUsers()
        {
            this.ActivitiesCalls = new HashSet<ActivitiesCalls>();
        }
    
        public int SiteUserID { get; set; }
        public string ASPNetUserID { get; set; }
        public string UserDisplayName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserJobTitle { get; set; }
        public string UserStatus { get; set; }
        public Nullable<int> UserProfileID { get; set; }
        public Nullable<int> PayrollSecurityID { get; set; }
        public int TimeZoneID { get; set; }
        public Nullable<int> SiteCoID { get; set; }
    
        public virtual ICollection<ActivitiesCalls> ActivitiesCalls { get; set; }
    }
}
