//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUserEmailOptions
    {
        public int SiteUserEmailOptionID { get; set; }
        public Nullable<int> SiteUserID { get; set; }
        public Nullable<bool> Cases { get; set; }
        public Nullable<bool> Events { get; set; }
        public Nullable<bool> Calls { get; set; }
        public Nullable<bool> WorkOrders { get; set; }
        public Nullable<bool> Purchases { get; set; }
        public Nullable<bool> Changes { get; set; }
        public Nullable<bool> Deliveries { get; set; }
        public Nullable<bool> Timekeeper { get; set; }
    }
}
