//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContactAddressTypes
    {
        public SiteContactAddressTypes()
        {
            this.CoContactAddresses = new HashSet<CoContactAddresses>();
        }
    
        public int AddressTypeID { get; set; }
        public string AddressTypeName { get; set; }
        public Nullable<int> AddressTypeOrder { get; set; }
    
        public virtual ICollection<CoContactAddresses> CoContactAddresses { get; set; }
    }
}
