//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUserOptions
    {
        public string ColorCode { get; set; }
        public Nullable<int> CalendarID { get; set; }
        public Nullable<int> CalendarGroupID { get; set; }
        public Nullable<double> StdRate { get; set; }
        public Nullable<double> OtRate { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string AcctUserID { get; set; }
        public Nullable<bool> CalendarDisplay { get; set; }
        public Nullable<int> CalendarLayout { get; set; }
        public Nullable<int> GridPageSize { get; set; }
        public string DashboardLayout { get; set; }
        public string DashboardWebPart1 { get; set; }
        public string DashboardWebPart2 { get; set; }
        public string DashboardWebPart3 { get; set; }
        public string DashboardCalendarLayout { get; set; }
        public Nullable<int> SkinID { get; set; }
        public string DockZoneState { get; set; }
        public int SiteUserID { get; set; }
    }
}
