//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUserGoogle
    {
        public string Refresh_Token { get; set; }
        public string Access_Token { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Expires_in { get; set; }
        public string Token_Type { get; set; }
        public int SiteUserID { get; set; }
    }
}
