//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContactEmailTypes
    {
        public SiteContactEmailTypes()
        {
            this.CoContactEmails = new HashSet<CoContactEmails>();
        }
    
        public int EmailTypeID { get; set; }
        public string EmailTypeName { get; set; }
    
        public virtual ICollection<CoContactEmails> CoContactEmails { get; set; }
    }
}
