//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePonti.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTimeZones
    {
        public int TimeZoneID { get; set; }
        public string TimeZoneName { get; set; }
        public Nullable<decimal> UTC { get; set; }
        public string Abbr { get; set; }
    }
}
